defaults:
  - scope:
      path: ''
    values:
      layout: 'page'
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
  - scope:
      path: ''
      type: 'destinations'
    values:
      layout: 'work'
  - scope:
      path: ''
      type: 'twentyfour-hours-in'
    values:
      layout: 'work'
  - scope:
      path: ''
      type: 'workshops'
    values:
      layout: 'workshop'

permalink: /blog/:year/:month/:day/:title/
url: http://quiet-herring.cloudvent.net

collections:
  destinations:
    output: true
    permalink: /destinations/:path/
  twentyfour-hours-in:
    output: true
    permalink: /24-hours-in/:path/
  workshops:
    output: true
    permalink: /workshop/:path/

floats: 
  - left
  - right

text-colors:
  - light
  - dark

sizes:
  - small
  - medium
  - large