defaults:
  - scope:
      path: ''
    values:
      layout: 'page'
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
  - scope:
      path: ''
      type: 'personalwork'
    values:
      layout: 'work'
  - scope:
      path: ''
      type: 'twentyfour-hours-in'
    values:
      layout: 'work'
  - scope:
      path: ''
      type: 'workshops'
    values:
      layout: 'workshop'
  - scope:
      path: ''
      type: 'weddings'
    values:
      layout: 'work'

permalink: /blog/:year/:month/:day/:title/
url: https://www.pieaerts.com

collections:
  personalwork:
    output: true
    permalink: /personal-work/:path/
  twentyfour-hours-in:
    output: true
    permalink: /24-hours-in/:path/
  workshops:
    output: true
    permalink: /workshop/:path/
  weddings:
    output: true
    permalink: /weddings/:path/

floats: 
  - left
  - right

text-colors:
  - light
  - dark

sizes:
  - small
  - medium
  - large