defaults:
  - scope:
      path: ''
    values:
      layout: 'page'
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
  - scope:
      path: ''
      type: 'destinations'
    values:
      layout: 'work'
  - scope:
      path: ''
      type: 'people-and-portraits'
    values:
      layout: 'lightbox_pap'
  - scope:
      path: ''
      type: 'city-life'
    values:
      layout: 'lightbox_cl'

permalink: /blog/:year/:month/:day/:title/

collections:
  destinations:
    output: true
    permalink: /destinations/:path/
  city-life:
    output: true
    permalink: /city-life/:path/
  people-and-portraits:
    output: true
    permalink: /people-and-portraits/:path/

floats: 
  - left
  - right